Documentation on Gazebo Harmonic migration
aerostack2/aerostack2.github.io pull request #59
Opened 2024-06-12 10:52 UTC by fjanguita

Installation guide to compile Aerostack2 using Gazebo Harmonic instead of Fortress

2024-06-12 11:06 UTC, RPS98 approved these changes

2024-06-12 11:31 UTC, miferco97 requested changes

2024-06-12 11:31 UTC, miferco97 commented on docs/_03_aerial_platforms/_gazebo_simulation/index.rst
> +After that, you can follow the `Gazebo Harmonic installation guide <https://gazebosim.org/docs/fortress/install_ubuntu>`__
Check this @fjanguita

2024-06-13 09:20 UTC, miferco97 approved these changes

2024-06-13 09:20 UTC, merged